services:
  - type: web
    name: majudrosiba
    env: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_TO
        value: vladimir.ansevics@gmail.com
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
